name: Merge Dev into Branches

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
          for branch in lea leo anais; do
            git checkout $branch
            git merge dev --no-edit
            git push origin $branch
          done